# Generated by Django 5.1.2 on 2024-11-01 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articlethema_thema_articlethema_thema_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlethema',
            name='is_main',
            field=models.BooleanField(blank=True, null=True, verbose_name='Основной'),
        ),
    ]
