# Generated by Django 5.1.2 on 2024-11-01 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_articlethema_is_main'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlethema',
            options={'verbose_name': 'Связь', 'verbose_name_plural': 'Связи'},
        ),
        migrations.AlterField(
            model_name='articlethema',
            name='is_main',
            field=models.BooleanField(blank=True, verbose_name='Основной'),
        ),
    ]
