# Generated by Django 5.1.3 on 2024-11-06 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='title',
            new_name='name',
        ),
    ]
