# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение датчиков
GET {{baseUrl}}/sensors/
Content-Type: application/json

###

# создание датчика
POST {{baseUrl}}/sensors/
Content-Type: application/json

{
  "title": "ESP00047",
  "description": "Датчик в гостиной"
}

###

# обновление датчика
PATCH {{baseUrl}}/sensors/update/9/
Content-Type: application/json

{
  "title": "ESP00044",
  "description": "Перенес датчик в 3 гостинную"
}

###

# добавление измерения
POST {{baseUrl}}/measurements/
Content-Type: application/json

{
  "sensor": 10,
  "temperature": 27
}

###

# получение информации по датчику
GET {{baseUrl}}/sensors/6/
Content-Type: application/json
